apiVersion: v1
kind: Service
metadata:
  name: admin-php-web-service
spec:
  selector:
    app: admin-php-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort
