apiVersion: v1
kind: Service
metadata:
  name: frontend-php-web-service
spec:
  selector:
    app: frontend-php-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      NodePort: 30000
  type: NodePort
